### ISSUE TITLE
incorrect output with vdr-2.3.4

### ISSUE THREAD

**Issue by 3PO** [rofafor/vdr-plugin-osdteletext#1]
Hi, 

i checked out the vdr-2.3.x branch and compiled it with vdr-2.3.4, but the output is incorrect:

![170429_113511](https://cloud.githubusercontent.com/assets/945108/25554600/6e18b6b8-2cd1-11e7-976a-dc6dc48a275f.jpg)

**Comment by rofafor** [comment]
It looks like you're not using any mono-spaced font (e.g. Courier:Bold).

**Comment by 3PO** [comment]
Hmmm....,

with this Repo: --> https://projects.vdr-developer.org/git/vdr-plugin-osdteletext.git/

and this patch: --> http://www.vdr-portal.de/board17-developer/board97-vdr-core/p1284413-produktive-problem-und-pluginl%C3%B6sungen-f%C3%BCr-vdr-2-3-2-und-h%C3%B6her/#post1284413


it works fine:

![170429_133628](https://cloud.githubusercontent.com/assets/945108/25555256/5d9e1d18-2ce1-11e7-9a91-39e3f3b827fb.jpg)

**Comment by rofafor** [comment]
I prefer the TTF support. Can we close the issue as you got your setup up and running?

**Comment by 3PO** [comment]
Sure, you can close it if you want.
