### ISSUE TITLE
Are you the currently active maintainer of this Plugin?

### ISSUE THREAD

**Issue by M-Reimer** [rofafor/vdr-plugin-osdteletext#5]
Hello,

I'm currently trying to create an overview about where the (currently still used) VDR plugins are currently maintained:

https://vdr-projects.github.io/

For unmaintained Plugins, I'm creating a (potentially temporary, depends on what a future maintainer wants to use) repository in context of this "vdr-projects" GitHub organization.

After looking through some repositories, it seems like you are the one who most recently did some updates to osdteletext and your repository is also the "most up-to-date".

So can I add your repository to my list or would you prefer if the Plugin gets a repository in context of the vdr-projects repository with you added as maintainer?

**Comment by rofafor** [comment]
I'm just maintaining this for myself and having https://projects.vdr-developer.org/projects/plg-osdteletext as upstream. My active VDR days are long gone - unfortunately, but willing to merge any upcoming pull requests.
